package jp.slm.business.bean;

// Generated 22 janv. 2014 15:00:53 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ArtistRateId generated by hbm2java
 */
@SuppressWarnings("serial")
@Embeddable
public class ArtistRateId implements java.io.Serializable
{

    private Long idArtist;

    private Long idUser;

    @Column(name = "id_artist", nullable = false)
    public Long getIdArtist()
    {
        return this.idArtist;
    }

    public void setIdArtist(Long idArtist)
    {
        this.idArtist = idArtist;
    }

    @Column(name = "id_user", nullable = false)
    public Long getIdUser()
    {
        return this.idUser;
    }

    public void setIdUser(Long idUser)
    {
        this.idUser = idUser;
    }

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((idArtist == null) ? 0 : idArtist.hashCode());
		result = prime * result + ((idUser == null) ? 0 : idUser.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) return true;
		if (obj == null) return false;
		if (getClass() != obj.getClass()) return false;
		ArtistRateId other = (ArtistRateId) obj;
		if (idArtist == null) {
			if (other.idArtist != null) return false;
		} else if (!idArtist.equals(other.idArtist)) return false;
		if (idUser == null) {
			if (other.idUser != null) return false;
		} else if (!idUser.equals(other.idUser)) return false;
		return true;
	}

	@Override
	public String toString() {
		return "ArtistRateId [idArtist=" + idArtist + ", idUser=" + idUser + "]";
	}
}
