package jp.slm.business.bean;

// Generated 22 janv. 2014 15:00:53 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import jp.slm.business.bean.generic.GenericLongIdBean;

/**
 * Avatar generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "avatar")
public class Avatar extends GenericLongIdBean
{
	@Transient
	public static final int SIZE = 100;
	
    private boolean isSystem = false;

    private Date inDate;

    private byte[] avatarData;

    @Column(name = "is_system", nullable = false)
    public boolean isIsSystem()
    {
        return this.isSystem;
    }

    public void setIsSystem(boolean isSystem)
    {
        this.isSystem = isSystem;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "in_date", nullable = false, length = 10)
    public Date getInDate()
    {
        return this.inDate;
    }

    public void setInDate(Date inDate)
    {
        this.inDate = inDate;
    }

    @Column(name = "avatar_data")
    public byte[] getAvatarData()
    {
        return this.avatarData;
    }

    public void setAvatarData(byte[] avatarData)
    {
        this.avatarData = avatarData;
    }
}
