package jp.slm.business.bean;

// Generated 22 janv. 2014 15:00:53 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import jp.slm.business.bean.generic.GenericLongIdBean;

/**
 * Bandmember generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "bandmember")
public class Bandmember extends GenericLongIdBean
{
    private Artist artist;

    private Long order;

    private String name;

    private Boolean gender;

    private Date birthdate;

    private String role;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_artist", nullable = false, insertable = false, updatable = false)
    public Artist getArtist()
    {
        return this.artist;
    }

    public void setArtist(Artist artist)
    {
        this.artist = artist;
    }

    @Column(name = "order", nullable = false)
    public Long getOrder()
    {
        return this.order;
    }

    public void setOrder(Long order)
    {
        this.order = order;
    }

    @Column(name = "name", nullable = false, length = 64)
    public String getName()
    {
        return this.name;
    }

    public void setName(String name)
    {
        this.name = name;
    }

    @Column(name = "gender")
    public Boolean getGender()
    {
        return this.gender;
    }

    public void setGender(Boolean gender)
    {
        this.gender = gender;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "birthdate", length = 10)
    public Date getBirthdate()
    {
        return this.birthdate;
    }

    public void setBirthdate(Date birthdate)
    {
        this.birthdate = birthdate;
    }

    @Column(name = "role", nullable = false, length = 64)
    public String getRole()
    {
        return this.role;
    }

    public void setRole(String role)
    {
        this.role = role;
    }

}
