package jp.slm.business.bean;

// Generated 22 janv. 2014 15:00:53 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import jp.slm.business.bean.generic.GenericLongIdBean;

/**
 * Comment generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "comment")
public class Comment extends GenericLongIdBean
{

    private Event event;

    private User user;

    private Picture picture;

    private Artist artist;

    private Mp3 mp3;

    private String comment;

    private Date dateIn;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_event", insertable = false, updatable = false)
    public Event getEvent()
    {
        return this.event;
    }

    public void setEvent(Event event)
    {
        this.event = event;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_user", nullable = false, insertable = false, updatable = false)
    public User getUser()
    {
        return this.user;
    }

    public void setUser(User user)
    {
        this.user = user;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_picture", insertable = false, updatable = false)
    public Picture getPicture()
    {
        return this.picture;
    }

    public void setPicture(Picture picture)
    {
        this.picture = picture;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_artist", insertable = false, updatable = false)
    public Artist getArtist()
    {
        return this.artist;
    }

    public void setArtist(Artist artist)
    {
        this.artist = artist;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_mp3", insertable = false, updatable = false)
    public Mp3 getMp3()
    {
        return this.mp3;
    }

    public void setMp3(Mp3 mp3)
    {
        this.mp3 = mp3;
    }

    @Column(name = "comment", nullable = false, length = 512)
    public String getComment()
    {
        return this.comment;
    }

    public void setComment(String comment)
    {
        this.comment = comment;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "date_in", nullable = false, length = 19)
    public Date getDateIn()
    {
        return this.dateIn;
    }

    public void setDateIn(Date dateIn)
    {
        this.dateIn = dateIn;
    }

}
