package jp.slm.business.bean;

// Generated 22 janv. 2014 15:00:53 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import jp.slm.business.bean.generic.GenericEmbeddedPkBean;

/**
 * EventRate generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "event_rate")
public class EventRate extends GenericEmbeddedPkBean<EventRateId>
{

    private Event event;

    private User user;

    private Long rate;

    @EmbeddedId
    @AttributeOverrides({
            @AttributeOverride(name = "idEvent", column = @Column(name = "id_event", nullable = false)),
            @AttributeOverride(name = "idUser", column = @Column(name = "id_user", nullable = false))})
    public EventRateId getId()
    {
        return this.id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_event", nullable = false, insertable = false, updatable = false)
    public Event getEvent()
    {
        return this.event;
    }

    public void setEvent(Event event)
    {
        this.event = event;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_user", nullable = false, insertable = false, updatable = false)
    public User getUser()
    {
        return this.user;
    }

    public void setUser(User user)
    {
        this.user = user;
    }

    @Column(name = "rate", nullable = false)
    public Long getRate()
    {
        return this.rate;
    }

    public void setRate(Long rate)
    {
        this.rate = rate;
    }

}
