package jp.slm.business.bean;

// Generated 22 janv. 2014 15:00:53 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * EventRateId generated by hbm2java
 */
@SuppressWarnings("serial")
@Embeddable
public class EventRateId implements java.io.Serializable
{

    private Long idEvent;

    private Long idUser;

    public EventRateId()
    {
    }

    public EventRateId(Long idEvent, Long idUser)
    {
        this.idEvent = idEvent;
        this.idUser = idUser;
    }

    @Column(name = "id_event", nullable = false)
    public Long getIdEvent()
    {
        return this.idEvent;
    }

    public void setIdEvent(Long idEvent)
    {
        this.idEvent = idEvent;
    }

    @Column(name = "id_user", nullable = false)
    public Long getIdUser()
    {
        return this.idUser;
    }

    public void setIdUser(Long idUser)
    {
        this.idUser = idUser;
    }

    public boolean equals(Object other)
    {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof EventRateId))
            return false;
        EventRateId castOther = (EventRateId) other;

        return (this.getIdEvent() == castOther.getIdEvent())
            && ((this.getIdUser() == castOther.getIdUser()) || (this.getIdUser() != null && castOther.getIdUser() != null && this
                .getIdUser().equals(castOther.getIdUser())));
    }

    public int hashCode()
    {
        int result = 17;

        result = 37 * result + (getIdEvent() == null ? 0 : this.getIdEvent().hashCode());
        result = 37 * result + (getIdUser() == null ? 0 : this.getIdUser().hashCode());
        return result;
    }

}
